"""initial schema

Revision ID: 77947f15140f
Revises: 
Create Date: 2026-04-21 20:37:00.197182

"""
from alembic import op
import sqlalchemy as sa


revision = '77947f15140f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('active_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_active_job_id'), 'chat_sessions', ['active_job_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('payee_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payee', name='uq_payee_mappings_payee')
    )
    op.create_index(op.f('ix_payee_mappings_id'), 'payee_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_payee_mappings_payee'), 'payee_mappings', ['payee'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_budget_url', sa.String(), nullable=True),
    sa.Column('actual_budget_password_encrypted', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('auto_sync_threshold', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('use_streaming', sa.String(), nullable=True),
    sa.Column('default_currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('pending_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('payee', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('actual_budget_id', sa.String(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_tx_confidence', 'pending_transactions', ['confidence', 'status', 'created_at'], unique=False)
    op.create_index('idx_pending_tx_job_created', 'pending_transactions', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pending_transactions_actual_budget_id'), 'pending_transactions', ['actual_budget_id'], unique=False)
    op.create_index(op.f('ix_pending_transactions_dedup_hash'), 'pending_transactions', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_pending_transactions_id'), 'pending_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_pending_transactions_job_id'), 'pending_transactions', ['job_id'], unique=False)
    op.create_index(op.f('ix_pending_transactions_message_id'), 'pending_transactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_pending_transactions_status'), 'pending_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_pending_transactions_upload_id'), 'pending_transactions', ['upload_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pending_transaction_id', sa.Integer(), nullable=False),
    sa.Column('actual_budget_transaction_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pending_transaction_id'], ['pending_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_pending_transactions_upload_id'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_status'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_message_id'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_job_id'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_id'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_dedup_hash'), table_name='pending_transactions')
    op.drop_index(op.f('ix_pending_transactions_actual_budget_id'), table_name='pending_transactions')
    op.drop_index('idx_pending_tx_job_created', table_name='pending_transactions')
    op.drop_index('idx_pending_tx_confidence', table_name='pending_transactions')
    op.drop_table('pending_transactions')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_payee_mappings_payee'), table_name='payee_mappings')
    op.drop_index(op.f('ix_payee_mappings_id'), table_name='payee_mappings')
    op.drop_table('payee_mappings')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_active_job_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
