"""initial schema

Revision ID: 9bba6aa2205f
Revises: 
Create Date: 2026-04-21 20:10:50.111682

"""
from alembic import op
import sqlalchemy as sa


revision = '9bba6aa2205f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
